### PR TITLE
Update Prerequisites in README.md

### PR DESCRIPTION
**Pull request by maheshschand**

### CODE REVIEW

**Comment by maheshschand** [comment]
This resolves a task in issue #40 . @sagar-sehgal Can you please review this?

**Comment by sagar-sehgal** [comment]
Seems to be great. @rajatkb you can have a look and then merge.

**Comment by maheshschand** [comment]
Sure.

**Comment by maheshschand** [comment]
@rajatkb I made necessary changes. Can you review it?

**Comment by maheshschand** [comment]
Can you merge this pull request too? @rajatkb @sagar-sehgal

**Pull request merged**
