### PR TITLE
Home page Design Implemented

### PR DESCRIPTION
**Pull request by Kajol-Kumari**
#17 

Label: Medium

Features added:
1. A basic Home page Created
2. Clicking on search-box will led to a new page.

Image for Reference:
https://files.slack.com/files-pri/TRN1H1V43-FUSLTL75F/screenshot_from_2020-03-09_16-10-43.png

https://files.slack.com/files-pri/TRN1H1V43-FV4KDT0EB/screenshot_from_2020-03-09_16-10-45.png

### CODE REVIEW

**Comment by anoopsingh1996** [comment]
@Kajol-Kumari  Use fxLayout grid system for responsive. In the current PR, you did not use any grid mechanism for responsiveness.

**Comment by Kajol-Kumari** [comment]
@anoopsingh1996 I added it in home page ,take a look and let me know if further changes are required

**Comment by anoopsingh1996** [comment]
> @anoopsingh1996 I added it in home page ,take a look and let me know if further changes are required

@Kajol-Kumari :+1:

**Comment by rajatkb** [comment]
@Kajol-Kumari  update the PR with latest design you showed me. Will have it merged.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari update the PR with latest design you showed me. Will have it merged.

Done @rajatkb

**Comment by anoopsingh1996** [comment]
@rajatkb Can you merge this PR I approved it.

**Comment by rajatkb** [comment]
@Kajol-Kumari   @anoopsingh1996   merged.

**Pull request merged**
