### PR TITLE
added_multiprocessing

### PR DESCRIPTION
**Pull request by abhishekgupta368**
#6 adding multiprocessing

Label: medium

Feature added:
I add multiprocessing in a file using pools

### CODE REVIEW

**Comment by rajatkb** [comment]
@abhishekgupta368  I will provide an interface make sure to implement that.

**Comment by rajatkb** [comment]
@abhishekgupta368  discuss the implementation during meetup, please. It's not what we require.

**Comment by abhishekgupta368** [comment]
No, there is problem in my git terminal due to which you got problematic file.
I am working on it.

**Comment by abhishekgupta368** [comment]
this is a error, I got:

```
Traceback (most recent call last):
  File "C:/Users/Lenovo/Desktop/open_src_notify/Conference-Notify/Scrapper-Service/app.py", line 95, in <module>
    lambda : scrapper(  log_level = log_level,
  File "C:\Users\Lenovo\Desktop\open_src_notify\Conference-Notify\Scrapper-Service\process\mutiprocessing.py", line 13, in execute_process
    p.start()
  File "C:\Users\Lenovo\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Lenovo\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Lenovo\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Lenovo\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Lenovo\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x000001C85F8E5BF8>: attribute lookup <lambda> on __main__ failed
2020-03-09 11:56:48,340 - __main__ - INFO - Scrapping done from all Scrapper plugins
```

**Comment by rajatkb** [comment]
Ya that's a legit error, because we are passing lambda functions which are not exactly pickable. i.e you cannot pickle them or covert to binary representation of objects. So hence the issue. Minor modifications should be able to help. You see if there is some hacky way of fixing this. 😅 I am looking into it too.

**Comment by abhishekgupta368** [comment]
ok

**Comment by abhishekgupta368** [comment]
hard work paid off

**Pull request merged**
