### PR TITLE
Frontend: Add conferences list and View Conference Page

### PR DESCRIPTION
**Pull request by Kajol-Kumari**
#85 [Feat.] Add list of events (all events) layout page
#86 [Feat.] Individual event details page layout

Required functionalities added:

- Add conferences to the page based on scroll event
- Clicking on the conference will view the particular conference.

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
ezgif com-video-to-gif
while fetching the conferences based on scroll event by the user, though the fetching is happening correctly but the html page is not getting updated accordingly. How can i achieve this?

**Comment by rajatkb** [comment]
create an array variable, in html iterate over the array elements to create the template. 
.
Populate i.e appand the new data in this array every time. U can also look into fireship tutorial for same. Asyn pipes can help also for this. https://youtu.be/Cy5MjeXZobE , this one is in firebase but principal would remain same.

**Comment by anoopsingh1996** [comment]
@Kajol-Kumari  Use Virtual scroll https://material.angular.io/cdk/scrolling/overview for achieving this.
Demo: https://stackblitz.com/edit/angular-virtual-scrolling

**Comment by Kajol-Kumari** [comment]
Hey @amandhamija98  please complete the assigned issue first as it is required by me for the functionality. Also i will be done with the functionality part maybe by tonight. Then u can work on the UI part after tackling the assigned issues.

Also @anoopsingh1996  If i am not wrong, virtual scroll will require the data to be fetched in hand and then display it according to the itemSize specified which will not satisfy our requirement. So i have done it through the approach siggeste dby @rajatkb  and it's working fine that way.

**Comment by amandhamija98** [comment]
Sure, I am almost done, will be submitting a PR soon

**Comment by rajatkb** [comment]
Make a draft PR Kajol for the problem u mentioned and the solution code so that we can review and suggest improvement if required.

**Comment by Kajol-Kumari** [comment]
@rajatkb @anoopsingh1996  current status of the functionality:

ezgif com-video-to-gif (1)

**Comment by rajatkb** [comment]
> 
> 
> @rajatkb @anoopsingh1996 current status of the functionality:
> 
> ezgif com-video-to-gif (1)

Looks fine functionally. Will have to work out the UI. I think @amandhamija98 's getOne request is needed as of now right ?

**Comment by Kajol-Kumari** [comment]
@rajatkb I have resolved the conflicts. Can u please merge it now.

**Pull request merged**
