### PR TITLE
Social Media profiles of Project handlers

### PR DESCRIPTION
**Pull request by roshankcjha**
Tabular arrangement of project mentors and Main admin as well as associating their social media profiles(Linkedin and GitHub)

### CODE REVIEW

**Comment by roshankcjha** [comment]
Hello @anoopsingh1996  @sagar-sehgal  @rajatkb  @MahamArif  Please review this PR and provide suggestions regarding it.

**Comment by roshankcjha** [comment]
I have done it with respect to **issue #40**.

**Comment by vipul-aggarwal-099** [comment]
I am ready to work on this Issue. Please do help with more details 👍

**Comment by rajatkb** [comment]
Can you explore this [All-Contributors](https://allcontributors.org/) , can be added in contributors tab. Looks like an interesting solution.

**Pull request merged**
